### ISSUE TITLE
Text folding control causes error

### ISSUE THREAD

**Issue by dawulf** [R-macos/Mac-GUI#2]
The controls for folding and unfolding code chunks seem to be buggy and generate errors in my R console.

I just downloaded an up-to-date R version (R 4.1.0 GUI 1.76 High Sierra build (7976)) on a new intel mac running 11.4 Big Sur and this happened the first time I used the code block folding buttons in the GUI. It doesn't always throw me the error message, and I can't find a clear pattern for when it does, but it's around once every 5 or so clicks on an expand/contract arrow button. It does seem to happen more often when my curser is in below the folding chunk. 

In the screenshots below, you can see the error message (also copied below) as well as the bug in the actual code folding (notice that the code chunk below the folded chunk is missing its first character). The error message is exactly the same every time it is delivered, except for the time reported as well as the final number in the "beyond bounds [0 .. 86]" line. If I wait a couple minutes and then cause the error again, that number gets a couple digits higher. 

Although R hasn't crashed from this yet, it gets very slow for a while when it happens. I know someone else tried to report this happening a couple years ago, and it was causing crashes for them: https://stat.ethz.ch/pipermail/r-sig-mac/2017-January/012192.html

Error text: 
```
2021-07-30 13:17:51.315 R[54765:1929193] *** RController: caught ObjC exception while processing system events. Update to the latest GUI version and consider reporting this properly (see FAQ) if it persists and is not known. 
*** reason: *** -[__NSArrayM objectAtIndex:]: index 18446744073709551615 beyond bounds [0 .. 86]
*** name: NSRangeException, info: (null)
*** Version: R 4.1.0 (80317) R.app R 4.1.0 GUI 1.76 High Sierra build
Consider saving your work soon in case this develops into a problem.
```
One time it followed up that error with:
```
2021-07-30 13:44:50.600 R[54765:1929193] !!! _NSLayoutTreeLineFragmentRectForGlyphAtIndex invalid glyph index 1965
```

Before the error:
![Screen Shot 2021-07-30 at 1 17 34 PM](https://user-images.githubusercontent.com/10604196/127710297-ca786979-9685-4e4c-96f4-f10f3a30069a.png)
After the error:
![Screen Shot 2021-07-30 at 1 18 25 PM](https://user-images.githubusercontent.com/10604196/127710340-c763832b-9d81-4486-803d-fb326c1bd04b.png)

Here is my sessionInfo:
```
sessionInfo()
R version 4.1.0 (2021-05-18)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Big Sur 11.4

Matrix products: default
BLAS:   /Library/Frameworks/R.framework/Versions/4.1/Resources/lib/libRblas.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/4.1/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods  
[7] base     

loaded via a namespace (and not attached):
[1] compiler_4.1.0 tools_4.1.0  
```

**Comment by s-u** [comment]
Thanks! This should be fixed now.

**Comment by dawulf** [comment]
Thank you @s-u !
